### ISSUE TITLE
Change AWG 5421 gain hardcoded value

### ISSUE THREAD

**Issue by odile9999** [pirenea-irap/PIL#23]
- modifier le VI AWG_5421_Load_Wfm_Script.vi

**Comment by odile9999** [comment]
- Gain à modifier de 0.31 à 0.16

**Comment by odile9999** [comment]
- Rajouter les filtres en sortie de la carte

**Comment by OdileCoeur-Joly** [comment]
* Le gain est toujours codé en dur, à passer en paramètre à AWG_5421_Load_Wfm_Script.vi
